image: dmattli/exopticonbuild:3

cache:
  key: "$CI_JOB_NAME"
  untracked: true
  paths:
  - cargo/
  - target/

# Set any required environment variables here
variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUST_BACKTRACE: FULL

stages:
  - build

app-build:
  stage: build
  before_script:
    - rustup component add clippy
  script:
    - cargo build --release
    - OPWD=`pwd`; cd exserial; cargo build; cd "$OPWD"
    - cargo clippy
    - cargo test



