image: debian:buster

cache:
  key: "$CI_JOB_NAME"
  untracked: true
  paths:
  - cargo/
  - target/

# Set any required environment variables here
variables:
  RUST_BACKTRACE: FULL
  GIT_SUBMODULE_STRATEGY: recursive
stages:
  - version
  - build
  - image
  - release

version:
  stage: version
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.19.0
  script:
    - release next-version --allow-current > .next-version
  artifacts:
    paths:
    - .next-version
  except:
  - tags

pre-release:
  stage: build
  image: dmattli/exopticon-build:devel
  script:
    - cargo make ci-flow
  only:
  - branches
  except:
  - master

build-image:
  stage: image
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  services:
  - docker:dind
  script:
  - rm -f build_info
  - echo "RELEASE_URL=https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/$CI_JOB_ID/artifacts/release" > build_info
  - echo "RELEASE_DESC=\"$(uname -mo) binary\"" >> build_info
  - echo "RELEASE_SHA=$CI_COMMIT_SHA" >> build_info
  - echo "RELEASE_VERSION=$(cat .next-version)" >> build_info
  - . build_info
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE:v$RELEASE_VERSION .
  - docker build -t $CI_REGISTRY_IMAGE:latest .
  - docker push $CI_REGISTRY_IMAGE:v$RELEASE_VERSION
  - docker push $CI_REGISTRY_IMAGE:latest

  artifacts:
     paths:
     - build_info
  only:
  - master

release:
  stage: release
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.19.0
  script:
  - rm -f release_info
  - mv build_info release_info
  - . release_info

  - release -v
  - release changelog
  - release commit-and-tag CHANGELOG.md release_info
  - release --ci-commit-tag v$RELEASE_VERSION add-download-link -n release -u $RELEASE_URL -d "$RELEASE_DESC"
  only:
  - master
