image: dmattli/exopticonbuild:4

cache:
  key: "$CI_JOB_NAME"
  untracked: true
  paths:
  - cargo/
  - target/

# Set any required environment variables here
variables:
  RUST_BACKTRACE: FULL

stages:
  - build

app-build:
  stage: build
  script:
    - cargo make
    - cargo clippy
    - cargo test



