[env]
CARGO_MAKE_RUN_CLIPPY = true
CARGO_MAKE_CLIPPY_ALLOW_FAIL = false
CARGO_MAKE_RUN_CHECK_FORMAT = true
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.ci-flow]
description = "CI task will run cargo build and cargo test with verbose output"
category = "CI"
dependencies = [
  "pre-ci-flow",
  "print-env-flow",
  "pre-build",
  "check-format-ci-flow",
  "clippy-ci-flow",
  "build-release",
  "post-build",
  "test-flow",
  "examples-ci-flow",
  "bench-ci-flow",
  "outdated-ci-flow",
  "ci-coverage-flow",
  "post-ci-flow",
]

[tasks.clippy-ci-flow]
condition = { env_set = [
  "CARGO_MAKE_RUN_CLIPPY",
] }

[tasks.check-format-ci-flow]
category = "CI"
condition = { env_set = [
  "CARGO_MAKE_RUN_CHECK_FORMAT",
] }

