-- Your SQL goes here

CREATE TABLE notification_contacts (
       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       group_name TEXT NOT NULL,
       username TEXT NOT NULL
);

ALTER TABLE alert_rules
RENAME COLUMN notification_topic TO contact_group;
