-- Your SQL goes here
CREATE TABLE alert_rule_cameras (
       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       alert_rule_id INTEGER NOT NULL REFERENCES alert_rules,
       camera_id INTEGER NOT NULL REFERENCES cameras
);
