version: '2.4'

services:
  caddy:
    image: quay.io/fariszr/caddy-dns:desec
    restart: always
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - caddy:/data
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
    environment:
      DOMAIN: ${DOMAIN}
      PORT: ${PORT}
      EMAIL: ${EMAIL}
      DESEC_TOKEN: ${DESEC_TOKEN}

volumes:
  caddy:
