version: '2.4'

services:
  db:
    image: docker.io/pgautoupgrade/pgautoupgrade:17-bookworm
    restart: always
    environment:
      POSTGRES_PASSWORD: ${EXOPTICON_POSTGRES_PASSWORD}
    volumes:
      - ${EXOPTICON_DB_PATH}:/var/lib/postgresql/data:Z
