version: '2.4'

services:
  exopticon:
    build:
      context: ..
      target: development
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:${EXOPTICON_POSTGRES_PASSWORD}@db
      - ROOT_URL
      - EXOPTICON_NAME
      - EXOPTICON_SHORT_NAME
    ports:
      - 0.0.0.0:3000:3000
    restart: always
    device_cgroup_rules:
      - 'a 189:* rwm'
    volumes:
      - cargo_home:/cargo
      - target:/exopticon/target
      - /dev/bus/usb:/dev/bus/usb
      - ..:/exopticon # map source directory for development
      - $EXOPTICON_VIDEO_PATH:/video
volumes:
  cargo_home:
  target:
