version: '2.4'

services:
  exopticon:
    image: dmattli/exopticon:v${RELEASE_VERSION}
    environment:
      DATABASE_URL: postgres://postgres:${EXOPTICON_POSTGRES_PASSWORD}@db
      TEST_DATABASE_URL: postgres://postgres:${EXOPTICON_POSTGRES_PASSWORD}@testdb
      ROOT_URL: "https://${DOMAIN}"
      DOMAIN: ${DOMAIN}
      EXOPTICON_NAME: ${EXOPTICON_NAME}
      EXOPTICON_SHORT_NAME: ${EXOPTICON_SHORT_NAME}
      RUST_LOG: ${RUST_LOG}
      EXOPTICON_METRICS_ENABLED: ${EXOPTICON_METRICS_ENABLED}
      EXOPTICON_METRICS_USERNAME: ${EXOPTICON_METRICS_USERNAME}
      EXOPTICON_METRICS_PASSWORD: ${EXOPTICON_METRICS_PASSWORD}
      EXOPTICON_WEBRTC_IPS: ${EXOPTICON_WEBRTC_IPS}
      EXOPTICON_WEBRTC_BUFFER_SIZE: ${EXOPTICON_WEBRTC_BUFFER_SIZE}
    restart: always
    ports:
      - 0.0.0.0:3000:3000
      - "4000:4000/udp"
    volumes:
      - $EXOPTICON_VIDEO_PATH:/video
      - /dev/bus/usb:/dev/bus/usb
