version: '2.4'

services:
  exopticon:
    image: dmattli/exopticon:v${RELEASE_VERSION}
    environment:
      - DATABASE_URL=postgres://postgres:${EXOPTICON_POSTGRES_PASSWORD}@db
      - RUST_LOG
      - ROOT_URL="https://${DOMAIN}"
      - DOMAIN
      - EXOPTICON_NAME
      - EXOPTICON_SHORT_NAME
      - EXOPTICON_METRICS_ENABLED
      - EXOPTICON_WEBRTC_IPS
      - EXOPTICON_WEBRTC_BUFFER_SIZE
    restart: always
    ports:
      - 0.0.0.0:3000:3000
      - "4000:4000/udp"
    devices: []
#      - /dev/apex_0:/dev/apex_0
    device_cgroup_rules:
      - 'a 189:* rwm'
    volumes:
      - $EXOPTICON_VIDEO_PATH:/video
      - /dev/bus/usb:/dev/bus/usb
