version: '2.4'

services:
  exopticon:
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: ${EXOPTICON_POSTGRES_PASSWORD}
    volumes:
      - type: bind
        source: ${EXOPTICON_DB_PATH}
        target: /var/lib/postgresql/data
