version: '2.4'

services:
  exopticon:
    build:
      context: .
      dockerfile: Dockerfile.cuda
      args:
        - RELEASE_VERSION=${RELEASE_VERSION}
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
