version: '2.4'

services:
  exopticon:
    env_file:
      - ../release_info
    image: dmattli/exopticon:v${RELEASE_VERSION}
    environment:
      DATABASE_URL: postgres://postgres:${EXOPTICON_POSTGRES_PASSWORD}@db
    restart: always
    devices:
      - /dev/bus/usb:/dev/bus/usb
    device_cgroup_rules:
      - 'a 189:*  rwm'
    volumes:
      - $EXOPTICON_VIDEO_PATH:/video
      - /dev/bus/usb:/dev/bus/usb
