version: '2.4'

services:
  exopticon:
    depends_on:
      - db
  db:
    image: pgautoupgrade/pgautoupgrade:17-bookworm
    restart: always
    environment:
      POSTGRES_PASSWORD: ${EXOPTICON_POSTGRES_PASSWORD}
    volumes:
      - type: bind
        source: ${EXOPTICON_DB_PATH}
        target: /var/lib/postgresql/data
  dbmetrics:
    image: quay.io/prometheuscommunity/postgres-exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: postgres://postgres:${EXOPTICON_POSTGRES_PASSWORD}@db?sslmode=disable
      PG_EXPORTER_INCLUDE_DATABASES: postgres
