version: '2.4'

services:
  caddy:
    build:
      context: .
      dockerfile: caddy.Dockerfile
    restart: always
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - caddy:/data
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      - DOMAIN
      - PORT
      - EMAIL
      - METRICS_AUTH_HASH
      - CLOUDFLARE_TOKEN

volumes:
  caddy:
