version: '2.4'

services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - caddy:/data
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      - DOMAIN
      - EMAIL
      - METRICS_AUTH_HASH

volumes:
  caddy:
