version: '2.4'

services:
  exopticon:
    image: dmattli/exopticon:v${RELEASE_VERSION}
    environment:
      - DATABASE_URL=postgres://postgres:${EXOPTICON_POSTGRES_PASSWORD}@db
      - ROOT_URL
      - EXOPTICON_NAME
      - EXOPTICON_SHORT_NAME

    restart: always
    ports:
      - 0.0.0.0:3000:3000
      - 3001:3001
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/apex_0:/dev/apex_0
    device_cgroup_rules:
      - 'a 189:* rwm'
    volumes:
      - $EXOPTICON_VIDEO_PATH:/video
      - /dev/bus/usb:/dev/bus/usb
