{
 "title": "Exopticon Analysis",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Camera Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(exopticon_capture_restart_count[1m])"
    }
   ]
  },
  {
   "title": "Analysis Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(exopticon_analysis_restart_count[5m])"
    }
   ]
  },
  {
   "title": "Analysis Frame Process Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(exopticon_analysis_process_count[5m])"
    }
   ]
  }
 ]
}