[package]
name = "onvif"
version = "0.1.0"
authors = ["David Matthew Mattli <dmm@mattli.us>"]
edition = "2018"

[dependencies]
base64 = "0.9"
bytes = "0.4"
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
hyper = "0.12"
futures = "0.1"
tokio = "0.1"
tokio-udp = "0.1"
rand = "0.6"
rust-crypto = "^0.2"
serde = "1.0.80"
serde_derive="1.0.79"
serde_json="1.0"
sxd-document = "0.3"
sxd-xpath = "0.4"
uuid = { version = "0.7.1", features = ["v4"] }