[package]
name = "exopticon"
description = "A video surveillance system."
version = "0.1.0"
repository = "https://gitlab.com/dmattli/exopticon"
authors = ["David Matthew Mattli <dmm@mattli.us>"]
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["camera", "cctv", "onvif", "surveillance"]
categories = ["web-programming"]
edition = "2018"
default-run = "exopticon"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
onvif = { path = "../onvif" }
exserial = { path = "../exserial" }
actix = "0.9.0"
actix-http = "^1.0.1"
actix-identity = "0.2"
actix-interop = "0.1"
actix-rt = "1.0"
actix-service = "1.0.5"
actix-web = "2.0.0"
actix-web-actors = "2.0.0"
actix-web-prom = "0.3"
base64 = "0.10.1"
base64-serde = "0.3"
bcrypt = "0.2"
bincode = "1.2.0"
bytes = "0.5"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.5"
dialoguer = "0.3"
diesel = { version = "1.4", features = ["postgres", "uuidv07", "r2d2", "chrono"] }
diesel_migrations = "1.4"
dotenv = "0.13"
env_logger = "0.5"
handlebars = "3.5.2"
lazy_static = "1.3.0"
log = "0.4"
mock_instant = "0.2"
mime_guess = "2.0.0-alpha.6"
mqtt-async-client = "0.1.5"
failure = "0.1"
qstring = "0.7.2"
prometheus = "^0.9"
rand = "^0.6"
rmp = "^0.8"
rmp-serde = "0.13"
futures = "0.3"
r2d2 = "0.8"
rust-embed = { version = "5.9.0", features = ["interpolate-folder-path"] }
telegram-bot = "0.7.0"
tempfile = "3.1.0"
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.3", features = ["codec"] }
tokio-process = "0.2"
serde_bytes = "0.10"
serde_derive="1.0"
serde_repr = "0.1"
serde_json="1.0"
serde = { version = "1.0", features = ["derive"] }
url = "^2.1"
uuid = { version = "0.7", features = ["serde", "v4"] }

[build-dependencies]
askama = "0.7"
