
[tasks.build-web]
category = "Build"
script = [
'''
cd web/
npm install
npm run check-format
npm run ng build -- --prod --configuration=production
'''
]

[tasks.watch-web]
description = "Watch the web/ dir for changes and build."
category = "Development"
script = [
'''
cd web/
npm run build -- --watch
'''
]

[tasks.pre-ci-flow]
category = "CI"
dependencies = [ "build-web" ]

[tasks.run]
description = "Runs the debug executable."
category = "Development"
command = "cargo"
args = ["run"]
dependencies = [ "build" ]

[tasks.build-release]
description = "Runs release build."
category = "Build"
command = "cargo"
args = ["build", "--release", "@@split(CARGO_MAKE_CARGO_BUILD_TEST_FLAGS, )"]
dependencies = [ "build-web" ]

[tasks.run-release]
description = "Runs the release executable."
category = "Development"
command = "cargo"
args = ["run", "--release"]
dependencies = [ "build-release" ]

