

[tasks.build-web]
category = "Build"
script = [
'''
cd web/
npm install
npm run ng build -- --prod
'''
]

[tasks.watch-web]
description = "Watch the web/ dir for changes and build."
category = "Development"
script = [
'''
cd web/
npm run build -- --watch
'''
]

[tasks.pre-build]
category = "Build"
dependencies = [ "build-web" ]

[tasks.run]
description = "Runs the debug executable."
category = "Development"
command = "cargo"
args = ["run"]
dependencies = [ "build" ]

[tasks.run-release]
description = "Runs the release executable."
category = "Development"
command = "cargo"
args = ["run", "--release"]
dependencies = [ "build-release" ]

